FROM waltyelnats/phaseregression:base
#need to copy this over separetely until finished
COPY 05.install_phaseprep.sh /src/install_scripts/05.install_phaseprep.sh
RUN bash /src/install_scripts/05.install_phaseprep.sh /opt > log_05_pr

#remove all install scripts
RUN rm -rf /src

#copy over pipeline
#COPY NHP_RestingState.py /opt/NHP_RestingState.py

RUN pip3 install pybids==0.6.5
